spring:
  r2dbc:
    username: postgres
    password: 123456
    url: r2dbc:postgresql://localhost:5432/cns-order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      validation-query: SELECT 1
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/cns-order
    baseline-on-migrate: true
  netty:
    leak-detection: paranoid
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false #for local development
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  application:
    name: cns-order-service

server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 3s
    idle-timeout: 15s

logging:
  level:
    inc.evil: debug
    org.zalando.logbook: trace

api:
  catalog-service-uri: "http://localhost:9001"

management:
  endpoints:
    web:
      exposure:
        include: '*'
