spring:
  r2dbc:
    username: postgres
    password: 123456
    url: r2dbc:postgresql://localhost:5432/cns-order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      validation-query: SELECT 1
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/cns-order
    baseline-on-migrate: true
  netty:
    leak-detection: paranoid

server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 3s
    idle-timeout: 15s

logging:
  level:
    inc.evil: debug
    org.zalando.logbook: trace

api:
  catalog-service-uri: "http://localhost:9001"

management:
  endpoints:
    web:
      exposure:
        include: '*'
