name: Commit Stage
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cns-book-store/cns-order-service
  VERSION: latest

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3 #check out current git repository
      - name: Set up JDK
        uses: actions/setup-java@v3 #install java runtime
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Code vulnerability scanning #scans for vulnerabilites
        uses: anchore/scan-action@v3
        id: scan #id for subsequent steps references
        with:
          path: "${{ github.workspace }}"
          fail-build: false #whether to fail or not the build based on security stuff
          severity-cutoff: high #minimum security cutoff
          acs-report-enable: true
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests #ensures gradle wrapper is executable and runs gradle build task
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Validate Kubernetes manifests
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.24.3
          kubeval: 0.16.1
          command: |
            kubeval --strict -d k8s
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/main' }} #only if on main branch
    needs: [ build ] #depends on the build stage
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build container image
        run: |
          chmod +x gradlew
          ./gradlew bootBuildImage  --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: OCI image vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          image:  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
